### ISSUE TITLE
ERROR: you did not specify a valid value for PXC_BOOTSTRAP environment variable

### ISSUE THREAD

**Issue by peterlavelle** [nixelsolutions/rancher-percona-xtradb-cluster#4]
Keep getting this error. Quick google search doesn't turn anything up that works. 

What's the valid values for this?

**Comment by nixelsolutions** [comment]
What version of the image are you using? Make sure to use the last one listed in https://hub.docker.com/r/nixel/rancher-percona-xtradb-cluster/tags/
